routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/patient/check', [\App\Http\Controllers\PatientController::class, 'check'])->name('patient.check');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user', \App\Http\Controllers\System\UserController::class);
Route::resource('patient', \App\Http\Controllers\PatientController::class);
Route::resource('inspection', \App\Http\Controllers\InspectionController::class);
Route::resource('employee', \App\Http\Controllers\EmployeeController::class);
Route::resource('database', \App\Http\Controllers\DataBaseController::class);
Route::resource('patient-referral', \App\Http\Controllers\PatientReferralController::class);
Route::resource('patient-examination', \App\Http\Controllers\PatientExaminationController::class);
Route::resource('report-excel', \App\Http\Controllers\ReportController::class)->only(['index', 'create']);
Route::resource('report-pdf', \App\Http\Controllers\ReportPdfController::class)->only(['index', 'edit']);

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Patient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = Patient::query();
        if (request()->ajax()) {
            return datatables()->of($result)
                ->addColumn('action', function ($data) {
                    $action = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $data->id . '" class="btnEdit btn btn-primary btn-sm">Edit</i></a>';
                    $action .= '&nbsp;';
                    $action .= '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $data->id . '" data-no_rekam_medis="' . $data->no_rekam_medis . '" class="btnRujuk btn btn-success btn-sm">Kirim</a>';

                    return $action;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        $employees = Employee::get();
        return view('patient.index', compact('employees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Patient $patient)
    {
        $this->validate($request, [
            'nama' => 'required',
            'nik' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'agama' => 'required',
            'telepon' => 'required',
            'alamat' => 'required',
            'jenis_kelamin' => 'required',
            'pekerjaan' => 'required',
        ]);

        try {
            $id = $request->get('id');
            $action = $id ? 'update' : 'create';

            $last = $patient->orderby('no_rekam_medis', 'desc')->first();

            if (isset($last->no_rekam_medis)) {
                $RM = $last->no_rekam_medis;
            } else {
                $RM = 00000;
            }

            $rekam_medis = str_pad($RM + 1, 6, 0, STR_PAD_LEFT);

            if ($action == 'create') {
                $patient->create(array_merge($request->except('id', 'no_rekam_medis'), [
                    'no_rekam_medis' => $rekam_medis,
                ]));
            } else {
                $patient::where('id', $id)
                    ->update($request->except('id', 'no_rekam_medis'));
            }

            return response()->json([
                'status' => 'success',
                'message' => 'Data has been ' . $action,
                'action' => $action,
            ], 201);
        } catch (\Exception$e) {
            return response()->json([
                'color' => 'red',
                'status' => 'error',
                'message' => $e->getMessage(),
            ], 401);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
        return response()->json([
            'patient' => $patient,
        ]);
    }

    public function check(Request $request)
    {
        $queryPasien = DB::table('patients as a')
            ->join('patient_referrals as b', 'b.patient_id', '=', 'a.id')
            ->where('b.token', '=', $request->key)
            ->select('a.id', 'a.*', 'b.token', 'b.kode_harian', 'b.id as patient_referral_id')
            ->first();

        $queryPemeriksaan = DB::table('patient_examinations as a')
            ->join('inspections as e', 'a.inspection_id', '=', 'e.id')
            ->where('a.patient_referral_id', '=', $queryPasien->patient_referral_id)
            ->select('a.id', 'a.hasil', 'a.tgl_pemeriksaan', 'a.pukul_pemeriksaan', 'e.uraian', 'e.satuan', 'e.nilai_normal')
            ->first();

        if (!isset($queryPasien)) {
            return abort(404, 'Administrator does not exist.');
        }

        return view('report.check', compact('queryPasien', 'queryPemeriksaan'));
    }
}

resources/views/patient/form.blade.php
<div class="modal fade" id="form-modal">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form">

                    <input type="hidden" id="id" name="id">

                    <div class="form-group" style="margin: 5px">
                        <label for="name" class="col-sm-2 control-label text-uppercase">No RM : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" required placeholder="Terisi Otomatis" id='no_rekam_medis' readonly>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="nik" class="col-sm-2 control-label text-uppercase">Nik : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="nik" name="nik" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="nama" class="col-sm-2 control-label text-uppercase">nama : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="nama" name="nama" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="tempat_lahir" class="col-sm-2 control-label text-uppercase">tempat lahir : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="tgl_lahir" class="col-sm-2 control-label text-uppercase">tgl lahir : </label>
                        <div class="col-sm-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" id="datepicker2" name="tgl_lahir" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="agama" class="col-sm-2 control-label text-uppercase">agama : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="agama" name="agama">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\AgamaEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="jenis_kelamin" class="col-sm-2 control-label text-uppercase">jenis kelamin : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="jenis_kelamin" name="jenis_kelamin">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\JenisKelaminEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="pekerjaan" class="col-sm-2 control-label text-uppercase">pekerjaan : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="pekerjaan" name="pekerjaan" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="telepon" class="col-sm-2 control-label text-uppercase">telepon : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="telepon" name="telepon" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="alamat" class="col-sm-2 control-label text-uppercase">alamat : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="alamat" name="alamat" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    {{-- <hr> --}}
                    {{-- <div class="form-group" style="margin: 5px">
                        <label for="password" class="col-sm-2 control-label text-uppercase">Gol Da : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="golongan_darah" name="golongan_darah" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="password" class="col-sm-2 control-label text-uppercase">tinggi badan : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="tinggi_badan" name="tinggi_badan" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group" style="margin: 5px">
                        <label for="password" class="col-sm-2 control-label text-uppercase">berat badan : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="berat_badan" name="berat_badan" required
                                placeholder="Input Here">
                        </div>
                    </div> --}}
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="submit">Save</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

resources/views/patient/index.blade.php
@extends('layouts.global')
@section('title') Pasien Manajemen @endsection
@section('content')
    <div class="box">
        <div class="box-header">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="box-title">Data Table Pasien</h3>
                </div>
                <div class="col-md-6 text-right">
                    <button type="button" class="btn btn-primary" id="tambahData">Tambah Data</button>
                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>RM</th>
                        <th>NIK</th>
                        <th>Nama</th>
                        <th>Alamat</th>
                        <th style="width: 100px">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <div class="row">
        @include('patient.referralForm')
        @include('patient.form')
    </div>
@endsection

@section('javascript')
    <script type="application/javascript">
        $('.select2').select2()


        $('#datepicker2').datepicker({
            todayBtn: 'linked',
            format: 'yyyy-mm-dd',
            autoclose: true
        });

        $('#datepicker3').datepicker({
            todayBtn: 'linked',
            format: 'yyyy-mm-dd',
            autoclose: true
        });

        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            let table = $('#table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('patient.index') }}",
                    type: 'GET'
                },
                columnDefs: [{
                    orderable: true,
                    className: 'text-center',
                    targets: [4]
                }],
                columns: [{
                    data: 'no_rekam_medis',
                }, {
                    data: 'nik',
                }, {
                    data: 'nama'
                }, {
                    data: 'alamat'
                }, {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                }],
                order: [
                    [0, 'asc']
                ]
            });
        });

        // show modal create
        $('#tambahData').click(function() {
            $('.modal-title').html('Tambah Data');
            $('#id').val('');
            $('#form').trigger("reset");
            $('#form-modal').modal('show');
        });

        // show modal edit
        $('body').on('click', '.btnEdit', function() {
            $('.modal-title').html('Edit Data');
            let id = $(this).data('id');
            $.get('patient/' + id + '/edit', function(data) {
                $('#form-modal').modal('show');
                $('#id').val(data.patient.id);
                $('#no_rekam_medis').val(data.patient.no_rekam_medis);
                $('#nama').val(data.patient.nama);
                $('#nik').val(data.patient.nik);
                $('#tempat_lahir').val(data.patient.tempat_lahir);
                $('#datepicker2').datepicker('setDate', data.patient.tgl_lahir);
                $('#agama').val(data.patient.agama);
                $('#telepon').val(data.patient.telepon);
                $('#alamat').val(data.patient.alamat);
                $('#jenis_kelamin').val(data.patient.jenis_kelamin);
                $('#pekerjaan').val(data.patient.pekerjaan);
                $('#golongan_darah').val(data.patient.golongan_darah);
                $('#tinggi_badan').val(data.patient.tinggi_badan);
                $('#berat_badan').val(data.patient.berat_badan);
            })
        });

        // post, put
        $('#submit').click(function(e) {
            e.preventDefault();
            $('#submit').html('Loading...');
            $.ajax({
                data: $('#form').serialize(),
                url: "{{ route('patient.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(data) {
                    toast(data)
                    $('#form').trigger("reset");
                    $('#submit').html('Save');
                    $('#form-modal').modal('hide');
                    let oTable = $('#table').dataTable();
                    oTable.fnDraw(false);
                },
                error: function(data) {
                    $('#submit').html('Save');
                    console.log('Error:', data);
                    toast(data)
                }
            });
        });

        // delete
        $(document).on('click', '.btnDelete', function() {
            if (confirm("Ingin menghapus data, data yg terhapus tidak bisa di kambalikan!")) {

                let id = $(this).attr('id');
                $.ajax({
                    url: "/patient/" + id,
                    type: 'delete',
                    success: function(data) {
                        toast(data);
                        setTimeout(function() {
                            let oTable = $('#table').dataTable();
                            oTable.fnDraw(false);
                        });
                    }
                })
            }
        });


        // show modal referral
        $('body').on('click', '.btnRujuk', function() {
            $('.modal-title').html('Edit Data');
            let id = $(this).data('id');
            let no_rekam_medis = $(this).data('no_rekam_medis');
            $('#patient_id').val(id);
            $('#no_rekam_medis_pasien').val(no_rekam_medis);
            $('.modal-title-referral').html('Rujukan Pemeriksaan');
            $('#form-modal-referral').modal('show');
        });

        // post, put referral
        $('#submit-referral').click(function(e) {
            e.preventDefault();
            $('#submit-referral').html('Loading...');
            $.ajax({
                data: $('#form-referral').serialize(),
                url: "{{ route('patient-referral.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(data) {
                    toast(data)
                    $('#form-referral').trigger("reset");
                    $('#submit-referral').html('Save');
                    $('#form-modal-referral').modal('hide');
                    let oTable = $('#table').dataTable();
                    oTable.fnDraw(false);
                },
                error: function(data) {
                    $('#submit-referral').html('Save');
                    console.log('Error:', data);
                    toast(data)
                }
            });
        });
    </script>
@endsection

resources/views/patient/referralForm.blade.php
<div class="modal fade" id="form-modal-referral">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title-referral"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form-referral">

                    <input type="hidden" id="patient_id" name="patient_id">

                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label text-uppercase">No RM : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" required placeholder="Terisi Otomatis"
                                id='no_rekam_medis_pasien' readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="catatan" class="col-sm-2 control-label text-uppercase">Catatan : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" required id='catatan' name="catatan" placeholder="Catatan Pemeriksaan">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tgl_rujukan" class="col-sm-2 control-label text-uppercase">Tgl Sample : </label>
                        <div class="col-sm-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" id="datepicker3" name="tgl_rujukan"
                                    autocomplete="off">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="analis" class="col-sm-2 control-label text-uppercase">Analis : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase select2" style="width: 100%;" id="analis" name="analis">
                                <option value="">--Pilih--</option>
                                @foreach ($employees as $key => $v)
                                @if ($v->kategori == 'Analis')
                                    <option value="{{ $v->id }}">{{ $v->nama }}</option>
                                @endif
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="dokter" class="col-sm-2 control-label text-uppercase">Dokter :
                        </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase select2" style="height: 100%; width: 100%;" id="dokter" name="dokter">
                                <option value="">--Pilih--</option>
                                @foreach ($employees as $key => $v)
                                @if ($v->kategori == 'Dokter')
                                    <option value="{{ $v->id }}">{{ $v->nama }}</option>
                                @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="submit-referral">Save</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</div>