routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/patient/check', [\App\Http\Controllers\PatientController::class, 'check'])->name('patient.check');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user', \App\Http\Controllers\System\UserController::class);
Route::resource('patient', \App\Http\Controllers\PatientController::class);
Route::resource('inspection', \App\Http\Controllers\InspectionController::class);
Route::resource('employee', \App\Http\Controllers\EmployeeController::class);
Route::resource('database', \App\Http\Controllers\DataBaseController::class);
Route::resource('patient-referral', \App\Http\Controllers\PatientReferralController::class);
Route::resource('patient-examination', \App\Http\Controllers\PatientExaminationController::class);
Route::resource('report-excel', \App\Http\Controllers\ReportController::class)->only(['index', 'create']);
Route::resource('report-pdf', \App\Http\Controllers\ReportPdfController::class)->only(['index', 'edit']);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $guarded = [];

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = Employee::query();
        if (request()->ajax()) {
            return datatables()->of($result)
                ->addColumn('action', function ($data) {
                    $action = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $data->id . '" class="btnEdit btn btn-primary btn-sm"><i class="fa fa-fw fa-edit"></i></a>';
                    $action .= '&nbsp;';
                    $action .= '<button type="button" name="delete" id="' . $data->id . '" class="btnDelete btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>';
                    return $action;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }
        return view('employee.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Employee $employee)
    {
        $this->validate($request, [
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'telepon' => 'required',
            'alamat' => 'required',
            'agama' => 'required',
            'kategori' => 'required',
        ]);

        try {
            $id = $request->get('id');
            $action = $id ? 'update' : 'create';
            if ($action == 'create') {
                $employee->create($request->except('id'));

            } else {
                $employee::where('id', $id)
                    ->update($request->except('id'));
            }

            return response()->json([
                'status' => 'success',
                'message' => 'Data has been ' . $action,
                'action' => $action,
            ], 201);
        } catch (\Exception$e) {
            return response()->json([
                'color' => 'red',
                'status' => 'error',
                'message' => $e->getMessage(),
            ], 401);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return response()->json([
            'employee' => $employee,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return response()->json([
            'status' => 'success',
            'message' => 'Data has been deleted',
        ], 201);
    }
}

resources/views/employee/form.blade.php
<div class="modal fade" id="form-modal">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form">

                    <input type="hidden" id="id" name="id">

                    <div class="form-group">
                        <label for="nama" class="col-sm-2 control-label text-uppercase">nama : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="nama" name="nama" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tempat_lahir" class="col-sm-2 control-label text-uppercase">tempat lahir : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" required
                                placeholder="Input Here">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tgl_lahir" class="col-sm-2 control-label text-uppercase">tgl lahir : </label>
                        <div class="col-sm-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" id="datepicker2" name="tgl_lahir" autocomplete="off">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="jenis_kelamin" class="col-sm-2 control-label text-uppercase">Jenis Kelamin : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="jenis_kelamin" name="jenis_kelamin">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\JenisKelaminEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="amaga" class="col-sm-2 control-label text-uppercase">Agama : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="agama" name="agama">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\AgamaEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="telepon" class="col-sm-2 control-label text-uppercase">telepon : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="telepon" name="telepon" required
                                placeholder="Input Here">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="alamat" class="col-sm-2 control-label text-uppercase">alamat : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="alamat" name="alamat" required
                                placeholder="Input Here">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="kategori" class="col-sm-2 control-label text-uppercase">kategori : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="kategori" name="kategori">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\EmployeeEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="submit">Save</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

resources/views/employee/index.blade.php
@extends('layouts.global')
@section('title') Employee Manajemen @endsection
@section('content')
    <div class="box">
        <div class="box-header">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="box-title">Data Table Employee</h3>
                </div>
                <div class="col-md-6 text-right">
                    <button type="button" class="btn btn-primary" id="tambahData">Tambah Data</button>
                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Tempat Lahir</th>
                        <th>Tgl Lahir</th>
                        <th>Telepon</th>
                        <th>Alamat</th>
                        <th>Kategori</th>
                        <th style="width: 100px">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <div class="row">
        @include('employee.form')
    </div>
@endsection

@section('javascript')
    <script type="application/javascript">
        $('#datepicker2').datepicker({
            todayBtn: 'linked',
            format: 'yyyy-mm-dd',
            autoclose: true
        });

        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            let table = $('#table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('employee.index') }}",
                    type: 'GET'
                },
                columnDefs: [{
                    orderable: true,
                    className: 'text-center',
                    targets: [6]
                }],
                columns: [{
                    data: 'nama',
                }, {
                    data: 'tempat_lahir',
                }, {
                    data: 'tgl_lahir'
                }, {
                    data: 'telepon'
                }, {
                    data: 'alamat'
                }, {
                    data: 'kategori'
                }, {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                }],
                order: [
                    [0, 'asc']
                ]
            });
        });

        // show modal create
        $('#tambahData').click(function() {
            $('.modal-title').html('Tambah Data');
            $('#id').val('');
            $('#form').trigger("reset");
            $('#form-modal').modal('show');
        });

        // show modal edit
        $('body').on('click', '.btnEdit', function() {
            $('.modal-title').html('Edit Data');
            let id = $(this).data('id');
            $.get('employee/' + id + '/edit', function(data) {
            $('#form-modal').modal('show');
                $('#id').val(data.employee.id);
                $('#nama').val(data.employee.nama);
                $('#tempat_lahir').val(data.employee.tempat_lahir);
                $('#datepicker2').datepicker('setDate', data.employee.tgl_lahir);
                $('#jenis_kelamin').val(data.employee.jenis_kelamin);
                $('#agama').val(data.employee.agama);
                $('#telepon').val(data.employee.telepon);
                $('#alamat').val(data.employee.alamat);
                $('#kategori').val(data.employee.kategori);
            })
        });

        // post, put
        $('#submit').click(function(e) {
            e.preventDefault();
            $('#submit').html('Loading...');
            $.ajax({
                data: $('#form').serialize(),
                url: "{{ route('employee.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(data) {
                    toast(data)
                    $('#form').trigger("reset");
                    $('#submit').html('Save');
                    $('#form-modal').modal('hide');
                    let oTable = $('#table').dataTable();
                    oTable.fnDraw(false);
                },
                error: function(data) {
                    $('#submit').html('Save');
                    console.log('Error:', data);
                    toast(data)
                }
            });
        });

        // delete
        $(document).on('click', '.btnDelete', function() {
            if (confirm("Ingin menghapus data, data yg terhapus tidak bisa di kambalikan!")) {

                let id = $(this).attr('id');
                $.ajax({
                    url: "/employee/" + id,
                    type: 'delete',
                    success: function(data) {
                        toast(data);
                        setTimeout(function() {
                            let oTable = $('#table').dataTable();
                            oTable.fnDraw(false);
                        });
                    }
                })
            }
        });
    </script>
@endsection