routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/patient/check', [\App\Http\Controllers\PatientController::class, 'check'])->name('patient.check');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user', \App\Http\Controllers\System\UserController::class);
Route::resource('patient', \App\Http\Controllers\PatientController::class);
Route::resource('inspection', \App\Http\Controllers\InspectionController::class);
Route::resource('employee', \App\Http\Controllers\EmployeeController::class);
Route::resource('database', \App\Http\Controllers\DataBaseController::class);
Route::resource('patient-referral', \App\Http\Controllers\PatientReferralController::class);
Route::resource('patient-examination', \App\Http\Controllers\PatientExaminationController::class);
Route::resource('report-excel', \App\Http\Controllers\ReportController::class)->only(['index', 'create']);
Route::resource('report-pdf', \App\Http\Controllers\ReportPdfController::class)->only(['index', 'edit']);

app/Models/PatientReferral.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PatientReferral extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function generateToken()
    {
        return Str::random(10);
    }
}

app/Http/Controllers/PatientReferralController.php
<?php

namespace App\Http\Controllers;

use App\Models\Inspection;
use App\Models\PatientExamination;
use App\Models\PatientReferral;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PatientReferralController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = DB::table('patient_referrals')
            ->join('patients', 'patients.id', '=', 'patient_referrals.patient_id')
            ->join('employees as analis', 'analis.id', '=', 'patient_referrals.analis')
            ->join('employees as dokter', 'dokter.id', '=', 'patient_referrals.dokter')
            ->select('patient_referrals.id', 'patient_referrals.tgl_rujukan', 'patient_referrals.catatan', 'patients.nama', 'patients.no_rekam_medis', 'analis.nama as analis', 'dokter.nama as dokter');

        if (request()->ajax()) {
            return datatables()->of($result)
                ->addColumn('action', function ($data) {
                    $action = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="' . $data->id . '" class="btnHasil btn btn-primary btn-sm">Hasil</a>';
                    $action .= '&nbsp;';
                    $patient = PatientExamination::where('patient_referral_id', $data->id)->first();

                    if (isset($patient)) {
                        $action .= '<a target="_blank" href="' . route('report-pdf.edit', $data->id) . '" class="btn btn-success btn-sm">Print</a>';
                    }

                    return $action;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        $inspections = Inspection::get();
        return view('patient-referral.index', compact('inspections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, PatientReferral $patientReferral)
    {
        $this->validate($request, [
            'patient_id' => 'required',
            'tgl_rujukan' => 'required',
            'catatan' => 'required',
            'analis' => 'required',
            'dokter' => 'required',
        ]);

        try {
            $id = $request->get('id');
            $action = $id ? 'update' : 'create';

            $today = \Carbon\Carbon::now();
            setlocale(LC_ALL, 'id_ID.UTF8', 'id_ID.UTF-8', 'id_ID.8859-1', 'id_ID', 'en_US.UTF8', 'en_US.UTF-8', 'en_US');
            \Carbon\Carbon::setLocale('id');
            $hari = substr(\Carbon\Carbon::parse($today)->isoFormat('dddd'), 0, 1);
            $tanggal = \Carbon\Carbon::parse($today)->isoFormat('D');
            $bulan = substr(\Carbon\Carbon::parse($today)->isoFormat('MMMM'), 0, 1);
            $kode = $hari . '' . $tanggal . '' . $bulan;

            $patientReferral->create(array_merge($request->except('token'), [
                'token' => PatientReferral::generateToken(),
                'kode_harian' => $kode,
            ]));

            return response()->json([
                'status' => 'success',
                'message' => 'Data has been ' . $action,
                'action' => $action,
            ], 201);
        } catch (\Exception$e) {
            return response()->json([
                'color' => 'red',
                'status' => 'error',
                'message' => $e->getMessage(),
            ], 401);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\PatientReferral  $patientReferral
     * @return \Illuminate\Http\Response
     */
    public function edit(PatientReferral $patientReferral)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\PatientReferral  $patientReferral
     * @return \Illuminate\Http\Response
     */
    public function destroy(PatientReferral $patientReferral)
    {
        $patientReferral->delete();
        return response()->json([
            'status' => 'success',
            'message' => 'Data has been deleted',
        ], 201);
    }
}

resources/views/patient-referral/form.blade.php
<div class="modal fade" id="form-modal">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form">

                    <input type="hidden" id="patient_referral_id" name="patient_referral_id">

                    <div class="form-group">
                        <label for="inspection_id" class="col-sm-2 control-label text-uppercase">Nama Pemeriksaan :
                        </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase select2" style="width: 100%;" id="inspection_id"
                                name="inspection_id">
                                <option value="">--Pilih--</option>
                                @foreach ($inspections as $key => $v)
                                    <option value="{{ $v->id }}">{{ $v->uraian }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tgl_pemeriksaan" class="col-sm-2 control-label text-uppercase">tgl pemeriksaan :
                        </label>
                        <div class="col-sm-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" id="datepicker3"
                                    name="tgl_pemeriksaan" autocomplete="off">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="pukul_pemeriksaan" class="col-sm-2 control-label text-uppercase">pukul pemeriksaan :
                        </label>
                        <div class="col-sm-10">
                            <input type="time" class="form-control" id="pukul_pemeriksaan" name="pukul_pemeriksaan"
                                required placeholder="Input Here">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="hasil" class="col-sm-2 control-label text-uppercase">Hasil : </label>
                        <div class="col-sm-10">
                            <select class="form-control text-uppercase" id="hasil" name="hasil">
                                <option value="">--Pilih--</option>
                                @foreach(App\Enums\HasilEnum::asSelectArray() as $key => $v)
                                <option value="{{ $v }}">{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="catatan" class="col-sm-2 control-label text-uppercase">catatan : </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="catatan" name="catatan" required
                                placeholder="Input Here">
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="submit">Save</button>
                </div>

                <table id="table-referral" class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th>Pemeriksaan</th>
                            <th>Tgl Pemeriksaan</th>
                            <th>Hasil</th>
                            <th>Catatan</th>
                            <th style="width: 100px">Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</div>

resources/views/patient-referral/index.blade.php
@extends('layouts.global')
@section('title') Patient Referral Manajemen @endsection
@section('content')
    <div class="box">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="box-title">Data Table Patient Referral</h3>
                </div>
                {{-- <div class="col-md-6 text-right">
                    <button type="button" class="btn btn-primary" id="tambahData">Tambah Data</button>
                </div> --}}
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>RM</th>
                        <th>Nama Pasien</th>
                        <th>Tgl Pemeriksaan</th>
                        <th>Catatan</th>
                        <th>Analis</th>
                        <th>Dokter</th>
                        <th style="width: 100px">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <div class="row">
        @include('patient-referral.form')
    </div>
@endsection

@section('javascript')
    <script type="application/javascript">
        $('#datepicker3').datepicker({
            todayBtn: 'linked',
            format: 'yyyy-mm-dd',
            autoclose: true
        });

        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            let table = $('#table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('patient-referral.index') }}",
                    type: 'GET'
                },
                columnDefs: [{
                    orderable: true,
                    className: 'text-center',
                    targets: [7]
                }],
                columns: [{
                    name: 'patients.id',
                    data: 'id',
                }, {
                    name: 'patients.no_rekam_medis',
                    data: 'no_rekam_medis',
                }, {
                    name: 'patients.nama',
                    data: 'nama',
                }, {
                    name: 'patient_referrals.tgl_rujukan',
                    data: 'tgl_rujukan'
                }, {
                    name: 'patient_referrals.catatan',
                    data: 'catatan',
                }, {
                    name: 'analis.nama',
                    data: 'analis',
                }, {
                    name: 'dokter.nama',
                    data: 'dokter',
                }, {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                }],
                order: [
                    [0, 'asc']
                ]
            });
        });

        // show modal create
        $('#tambahData').click(function() {
            $('.modal-title').html('Tambah Data');
            $('#id').val('');
            $('#form').trigger("reset");
            $('#form-modal').modal('show');
        });

        // show modal edit
        $('body').on('click', '.btnHasil', function() {
            $('.modal-title').html('Form Pemeriksaan');
            let id = $(this).data('id');
            $('#patient_referral_id').val(id);
            $('#form-modal').modal('show');

            let table = $('#table-referral').DataTable({
                processing: true,
                bDestroy: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('patient-examination.index') }}",
                    data: {
                        id: id,
                    },
                    type: 'GET'
                },
                columnDefs: [{
                    orderable: true,
                    className: 'text-center',
                    targets: [4]
                }],
                columns: [{
                    name: 'inspections.uraian',
                    data: 'uraian',
                }, {
                    name: 'tgl_pemeriksaan',
                    data: 'tgl_pemeriksaan',
                }, {
                    name: 'hasil',
                    data: 'hasil',
                }, {
                    name: 'catatan',
                    data: 'catatan',
                }, {
                    data: 'action',
                    orderable: false,
                    searchable: false,
                }],
                order: [
                    [0, 'asc']
                ]
            });

        });

        // post, put
        $('#submit').click(function(e) {
            e.preventDefault();
            $('#submit').html('Loading...');
            $.ajax({
                data: $('#form').serialize(),
                url: "{{ route('patient-examination.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(data) {
                    toast(data)
                    $('#form').trigger("reset");
                    $('#submit').html('Save');
                    let oTable = $('#table-referral').dataTable();
                    oTable.fnDraw(false);
                    let tTable = $('#table').dataTable();
                    tTable.fnDraw(false);
                },
                error: function(data) {
                    $('#submit').html('Save');
                    console.log('Error:', data);
                    toast(data)
                }
            });
        });

        // delete
        $(document).on('click', '.btnDelete', function() {
            if (confirm("Ingin menghapus data, data yg terhapus tidak bisa di kambalikan!")) {

                let id = $(this).data('id');
                $.ajax({
                    url: "/patient-examination/" + id,
                    type: 'delete',
                    success: function(data) {
                        toast(data);
                        setTimeout(function() {
                            let oTable = $('#table-referral').dataTable();
                            oTable.fnDraw(false);
                            let tTable = $('#table').dataTable();
                            tTable.fnDraw(false);
                        });
                    }
                })
            }
        });
    </script>
@endsection